#!/bin/sh

export PATH=$PATH:/usr/local/bin:/usr/local/sbin
base=/var/cfengine

if [ "$(pwd)" != "/var/cfengine/inputs/config" ]
then
	echo "You must start this script from the /var/cfengine/inputs/config directory"
	exit 1
fi

(ksh ./scripts/make-agent.conf)
/var/cfengine/sbin/cfagent -KqI -f /var/cfengine/inputs/agent.conf 2>&1 \
	| grep -v "Executing script" \
	| grep -v "Finished script"
	

