#!/bin/sh

SITE=$(hostname | cut -d"." -f2-)
HOST=$(hostname -s)

cd /var/cfengine/inputs/config

if [ "$1" != "manual" ]
then
	sleep $(jot -nr 1 1 800)
fi

touch /root/.cvspass

for i in features scripts
do
	(cd ${i} && nice -n 15 cvs -q -d :pserver:anonymous@cvs.mci.berlios.de:/cvsroot/mci update -Pd)
done

for i in sites hosts
do	
	(cd ${i} && \
	CVSROOT=":ext:anoncvs@gold.${SITE}:/home/repositories/cvs/infrastructure" \
	CVS_RSH="ssh" \
	nice -n 15 cvs -q update -Pd 2>&1 \
	| grep -v "^ssh: connect to host gold.${SITE} port 22: Connection timed out" \
	| grep -v "end of file from server")
done
