#!/bin/sh

SITE=$(hostname | cut -d"." -f2-)
HOST=$(hostname -s)

IF=${1}

cd /etc/djbdns/tinydns-${1}/root

cp /var/cfengine/inputs/config/sites/${SITE}/dns/data data.new

if [ ! -d "/var/cfengine/inputs/config/hosts/${SITE}/${HOST}/network/intranet" ] && [ "$(grep vpn /var/cfengine/inputs/config/hosts/${SITE}/${HOST}/features.list)" ]
then
	cd /var/cfengine/inputs/config/hosts/${SITE}
	for i in $(find * -type d -maxdepth 0 -mindepth 0 | grep -v CVS | grep -v svn | grep -v ${HOST})
	do
		cd /var/cfengine/inputs/config/hosts/${SITE}/${i}
		VPN_IP=""
		if [ -d "network/intranet" ]
		then
			INTRANET_IP=$(cat network/intranet/*/ipv4/address | head -1)
		else
			INTRANET_IP=""
		fi
		if [ -f "features.list" ] && [ "$(grep vpnClient features.list | wc -l)" -eq "1" ]
		then
			VPN_IP=$(cat network/vpn/tun0/ipv4/address)
		fi
		if [ -f "features.list" ] && [ "$(grep vpnServer features.list | wc -l)" -eq "1" ]
		then
			VPN_IP=$(cat /var/cfengine/inputs/config/hosts/${SITE}/${HOST}/network/vpn/tun0/ipv4/dest)
		fi
		if [ -n "$VPN_IP" ] && [ -n "$INTRANET_IP" ]
		then
			cd /etc/djbdns/tinydns-${IF}/root
			cat data.new | sed -e "s|${INTRANET_IP}$|${VPN_IP}|g" > data.tmp
			mv data.tmp data.new
		fi
	done
fi	
mv data.new data	

if [ -f "data" ]
then
	tinydns-data
fi
