#!/bin/ksh

export PATH=$PATH:/var/qmail/bin:/usr/local/bin

if [ -z "$SERVICE" ] || [ -z "$FILTER" ]
then
	echo "need SERVICE and FILTER parameter"
	exit 1
fi

site=$(cat /etc/myname | sed -e "s|$(hostname -s).||")

yesterday=$(( $(date +%s) - (60 * 60 * 24) ))

logDir=$(date -r $yesterday +/service/$SERVICE/log/main/log.%Y-%m-%d)
date=$(date -r $yesterday +%d-%m-%Y)

if [ -d "$logDir" ]
then
	cd $logDir
	lines=$(cat * | $FILTER | wc -l)
	if [ $lines != 0 ]
	then
		(echo "Subject: $SERVICE logs for $date"; echo "" && cat * | $FILTER ) | $PROGRAM tai64nlocal | qmail-inject root@${SITE}
	fi
fi

