#!/bin/sh

HOST=$(hostname -s)
SITE=$(hostname | cut -d"." -f2-)

BASE_CONFIG=/var/cfengine/inputs/config/hosts/${SITE}/${HOST}/dns

if [ ! -d "${BASE_CONFIG}" ] 
then
	exit 0 
fi

cd ${BASE_CONFIG}

if [ ! -d "${BASE_CONFIG}/transfer" ]
then
	exit 0 
fi

rm -f /etc/crontab.d/axfrdns
touch /etc/crontab.d/axfrdns

cd ${BASE_CONFIG}/transfer

for i in $(find * -type f -maxdepth 0 -mindepth 0)
do
	cd ${BASE_CONFIG}/transfer
	IP=$(cat ${i})
	IF=${i}
	mkdir -p /var/log/djbdns/axfrdns-${IF}
	chown _syslogd:_syslogd /var/log/djbdns/axfrdns-${IF}
	chmod 700 /var/log/djbdns/axfrdns-${IF}

	mkdir -p /etc/djbdns/axfrdns-${IF}
	chown root:wheel /etc/djbdns/axfrdns-${IF}
	chmod 1755 /etc/djbdns/axfrdns-${IF}

        mkdir -p /etc/djbdns/axfrdns-${IF}/log
        chown root:wheel /etc/djbdns/axfrdns-${IF}/log
        chmod 755 /etc/djbdns/axfrdns-${IF}/log

        mkdir -p /etc/djbdns/axfrdns-${IF}/env
        chown root:wheel /etc/djbdns/axfrdns-${IF}/env
        chmod 755 /etc/djbdns/axfrdns-${IF}/env

	echo ${IP} > /etc/djbdns/axfrdns-${IF}/env/IP
	chmod 644 /etc/djbdns/axfrdns-${IF}/env/IP

	echo "/etc/djbdns/tinydns-${IF}/root" > /etc/djbdns/axfrdns-${IF}/env/ROOT
	chmod 644 /etc/djbdns/axfrdns-${IF}/env/ROOT

	cp /var/cfengine/inputs/config/features/dnsTransfer/scripts/run.log /etc/djbdns/axfrdns-${IF}/log/run
	chmod 755 /etc/djbdns/axfrdns-${IF}/log/run

	cp /var/cfengine/inputs/config/features/dnsTransfer/scripts/run /etc/djbdns/axfrdns-${IF}/run
	chmod 755 /etc/djbdns/axfrdns-${IF}/run

	cd /service
	ln -snf /etc/djbdns/axfrdns-${IF} axfrdns-${IF} 
	cd /etc/djbdns/axfrdns-${IF}/log
	ln -snf /var/log/djbdns/axfrdns-${IF} main

	echo "0 0 * * * svc -t /service/axfrdns-${IF}/log" >> /etc/crontab.d/axfrdns
	echo "11 * * * * /bin/ksh /var/cfengine/inputs/config/features/dnsTransfer/logging/mail_logs_axfrdns.sh ${IF}" >> /etc/crontab.d/axfrdns
	
done
