#!/bin/sh

SITE=$(hostname | cut -d"." -f2-)
HOST=$(hostname -s)

cd /${SITE}/${HOST}/data

if [ -d "zope" ] && [ $(find zope -type d -name log -mindepth 2 -maxdepth 2 | wc -l) ]
then
	cd zope
	for i in $(find * -type d -name log -maxdepth 1 -mindepth 1)
	do
		cd /${SITE}/${HOST}/data/zope/${i}
		if [ -f "event.log" ] && [ $(ls -sk event.log | sed -e "s|^ ||g" | cut -d" " -f1) -gt 400 ]
		then 
			cp event.log event.log.old
			echo "" > event.log
		fi
                if [ -f "Z2.log" ] && [ $(ls -sk Z2.log | sed -e "s|^ ||g" | cut -d" " -f1) -gt 400 ]
                then
                        cp Z2.log Z2.log.old
                        echo "" > Z2.log
                fi
	done
fi
